"use client"
import Link from "next/link"
import { Nav } from "../../components/nav"

export function InsightsClient({ snapshot, weekly }: {
  snapshot: Record<string, unknown> | null
  weekly: Record<string, unknown> | null
}) {
  const headline = (weekly?.headline as string) ?? null
  const body = (weekly?.body as string) ?? null
  const trendDirection = (weekly?.trend_direction as string) ?? "stable"

  const trendLabel = trendDirection === "improving" ? "↑ Improving" : trendDirection === "declining" ? "↓ Declining" : "→ Stable"
  const trendColor = trendDirection === "improving" ? "var(--status-optimal-text, #27500A)" : trendDirection === "declining" ? "var(--status-attention-text, #791F1F)" : "var(--ink-40)"

  return (
    <div className="min-h-svh bg-off-white">
      <Nav />
      <main style={{ maxWidth: 680, margin: "0 auto", padding: "32px 24px 80px" }}>

        {/* Header */}
        <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between", marginBottom: 8 }}>
          <h1 style={{ fontFamily: "var(--font-manrope), system-ui, sans-serif", fontSize: 36, fontWeight: 300, color: "var(--ink)", margin: 0 }}>
            AI Insights
          </h1>
          <Link href="/dashboard" style={{ fontFamily: "var(--font-body)", fontSize: 11, textTransform: "uppercase", letterSpacing: "0.06em", color: "var(--ink-30)", textDecoration: "none" }}
            onMouseEnter={e => { e.currentTarget.style.color = "#C49A3C" }}
            onMouseLeave={e => { e.currentTarget.style.color = "var(--ink-30)" }}>
            ← Dashboard
          </Link>
        </div>

        {/* Hero */}
        <div style={{ marginBottom: 48 }}>
          <p style={{ fontFamily: "var(--font-manrope), system-ui, sans-serif", fontStyle: "italic", fontSize: 22, lineHeight: 1.4, color: "var(--ink)", margin: "0 0 16px" }}>
            Your data, interpreted.
          </p>
          <p style={{ fontFamily: "var(--font-body)", fontSize: 14, lineHeight: 1.7, color: "var(--ink-60)", margin: 0, maxWidth: 560 }}>
            Each insight connects signals across your panels. They are generated from your actual measurements — not generic recommendations.
          </p>
        </div>

        {/* Weekly narrative */}
        {headline && (
          <div style={{
            borderLeft: "3px solid var(--color-accent-gold, #C49A3C)",
            background: "var(--ink-04, rgba(20,20,16,0.04))",
            borderRadius: "0 10px 10px 0",
            padding: "20px 24px",
            marginBottom: 32,
          }}>
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 10 }}>
              <p style={{ fontFamily: "var(--font-body)", fontSize: 10, textTransform: "uppercase", letterSpacing: "0.08em", color: "var(--ink-30)", margin: 0 }}>
                Weekly snapshot
              </p>
              <span style={{ fontFamily: "var(--font-body)", fontSize: 11, color: trendColor, fontWeight: 500 }}>
                {trendLabel}
              </span>
            </div>
            <p style={{ fontFamily: "var(--font-manrope), system-ui, sans-serif", fontSize: 19, lineHeight: 1.4, color: "var(--ink)", margin: "0 0 10px" }}>
              {headline}
            </p>
            {body && (
              <p style={{ fontFamily: "var(--font-body)", fontSize: 13, color: "var(--ink-60)", lineHeight: 1.6, margin: 0 }}>
                {body}
              </p>
            )}
          </div>
        )}

        {!headline && (
          <div style={{
            background: "var(--peaq-bg-secondary, #F0EFE8)",
            borderRadius: 10,
            padding: 24,
            marginBottom: 32,
          }}>
            <p style={{ fontFamily: "var(--font-manrope), system-ui, sans-serif", fontStyle: "italic", fontSize: 17, color: "var(--ink-40)", lineHeight: 1.4, margin: 0 }}>
              Your weekly AI insight will appear here once enough data is available.
            </p>
          </div>
        )}

        {/* About */}
        <p style={{ fontFamily: "var(--font-body)", fontSize: 13, color: "var(--ink-40)", lineHeight: 1.7, maxWidth: 520 }}>
          Insights are generated by analyzing your actual panel data against peer-reviewed clinical thresholds. They update when your data updates. They are not medical advice — always discuss significant findings with your healthcare provider.
        </p>
      </main>
    </div>
  )
}
