/**
 * Auto-generated by: supabase gen types typescript --project-id <your-project-id>
 * Run: npm run db:types (see root package.json scripts)
 *
 * This file is checked into git as a stub.
 * After setting up your Supabase project, regenerate with:
 *   npx supabase gen types typescript --project-id YOUR_PROJECT_ID > packages/api-client/src/supabase/database.types.ts
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          first_name: string
          last_name: string
          created_at: string
          updated_at: string
          junction_user_id: string | null
          onboarding_step: string | null
          onboarding_completed: boolean
        }
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      wearable_connections: {
        Row: {
          id: string
          user_id: string
          provider: string
          junction_user_id: string
          status: string
          connected_at: string
          last_sync_at: string | null
          retro_nights: number | null
        }
        Insert: Omit<Database['public']['Tables']['wearable_connections']['Row'], 'id' | 'connected_at'>
        Update: Partial<Database['public']['Tables']['wearable_connections']['Insert']>
      }
      lab_results: {
        Row: {
          id: string
          user_id: string
          source: string
          lab_name: string | null
          collection_date: string
          uploaded_at: string
          hs_crp_mgl: number | null
          vitamin_d_ngml: number | null
          apob_mgdl: number | null
          ldl_mgdl: number | null
          hdl_mgdl: number | null
          triglycerides_mgdl: number | null
          lpa_mgdl: number | null
          glucose_mgdl: number | null
          hba1c_pct: number | null
          esr_mmhr: number | null
          homocysteine_umoll: number | null
          ferritin_ngml: number | null
          junction_parser_job_id: string | null
          parser_status: string | null
          raw_pdf_storage_path: string | null
        }
        Insert: Omit<Database['public']['Tables']['lab_results']['Row'], 'id' | 'uploaded_at'>
        Update: Partial<Database['public']['Tables']['lab_results']['Insert']>
      }
      oral_kit_orders: {
        Row: {
          id: string
          user_id: string
          ordered_at: string
          status: string
          tracking_number: string | null
          zymo_report_id: string | null
          shannon_diversity: number | null
          nitrate_reducers_pct: number | null
          periodontopathogen_pct: number | null
          osa_taxa_pct: number | null
          collection_date: string | null
        }
        Insert: Omit<Database['public']['Tables']['oral_kit_orders']['Row'], 'id' | 'ordered_at'>
        Update: Partial<Database['public']['Tables']['oral_kit_orders']['Insert']>
      }
      lifestyle_records: {
        Row: {
          id: string
          user_id: string
          answered_at: string
          updated_at: string
          exercise_level: string
          brushing_freq: string
          flossing_freq: string
          mouthwash_type: string
          last_dental_visit: string
          smoking_status: string
          known_hypertension: boolean
          known_diabetes: boolean
          sleep_duration: string
          sleep_latency: string
          sleep_qual_self: string
          daytime_fatigue: string
          night_wakings: string
          sleep_medication: string
          // V5 additions
          hs_crp_available: boolean
          vo2_source: string | null
          vo2_manual: number | null
          antibiotics_last_60d: boolean
          antibiotics_last_90d: boolean
          medications: string[] | null
          eosinophil_history: boolean
          oma_qc_pass: boolean | null
          hs_crp_qc_pass: boolean | null
        }
        Insert: Omit<Database['public']['Tables']['lifestyle_records']['Row'], 'id' | 'answered_at'>
        Update: Partial<Database['public']['Tables']['lifestyle_records']['Insert']>
      }
      score_snapshots: {
        Row: {
          id: string
          user_id: string
          calculated_at: string
          engine_version: string
          score: number
          category: string
          sleep_sub: number
          sleep_source: string
          blood_sub: number
          oral_sub: number
          lifestyle_sub: number
          interaction_pool: number
          lab_result_id: string | null
          oral_kit_id: string | null
          wearable_connection_id: string | null
          lifestyle_record_id: string | null
          lab_freshness: string
          // Peaq Age V5 fields
          peaq_age: number | null
          pheno_age: number | null
          oma_percentile: number | null
          vo2_percentile: number | null
          rhr_delta: number | null
          sleep_dur_delta: number | null
          sleep_reg_delta: number | null
          cross_panel_i1: number | null
          cross_panel_i2: number | null
          cross_panel_i3: number | null
          peaq_age_delta: number | null
          peaq_age_band: string | null
          score_version: string
          peaq_age_breakdown: Record<string, unknown> | null
        }
        Insert: Omit<Database['public']['Tables']['score_snapshots']['Row'], 'id'>
        Update: Partial<Database['public']['Tables']['score_snapshots']['Insert']>
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
